title: PYQ Archive
description: >- # this means to ignore newlines until "baseurl:"
  A collection of previous year question papers for Graphic Era Hill University semester examinations.
baseurl: "/pyqs"
url: ""
logo: "/assets/images/logo.png"
# Build settings

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: Lakshyajeet Jalal
  email: lakshyajeetjalal@duck.coms

minima:
  skin: auto
  social_links:
    - { platform: telegram, user_url: "https://t.me/mglsj" }
    - { platform: github, user_url: "https://github.com/MG-LSJ" }
    - {
        platform: linkedin,
        user_url: "https://www.linkedin.com/in/lakshyajeet-jalal/",
      }

header_pages:
  - about.md

feed:

host: 0.0.0.0
port: 7000

collections:
  pyqs:
    output: true
    permalink: /:path

liquid:
  error_mode: strict

sass:
  implementation: sassc
  style: compact
  sass_dir: _sass
  line_comments: false
  sourcemap: always

exclude:
  - "generate.py"
  - "run.bat"
